# fly.toml app configuration file generated for online-board-game on 2023-05-16T17:22:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "online-board-game"
primary_region = "waw"

[env]
  ASPNETCORE_URLS="http://+:8080"

[build]
  image = "student232323/online-board-game:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
