export enum FieldType {
  CHAMBER_I = 'CHAMBER_I',
  CHAMBER_L = 'CHAMBER_L',
  CHAMBER_T = 'CHAMBER_T',
  CHAMBER_X = 'CHAMBER_X',
  CORRIDOR_I = 'CORRIDOR_I',
  CORRIDOR_L = 'CORRIDOR_L',
  CORRIDOR_T = 'CORRIDOR_T',
  CORRIDOR_X = 'CORRIDOR_X',
  HEALING_I = 'HEALING_I',
  HEALING_L = 'HEALING_L',
  HEALING_T = 'HEALING_T',
  HEALING_X = 'HEALING_X',
  EMPTY_FIELD = 'EMPTY_FIELD'
}
